name:        dynet-tools
version:     0.1.0.4
# synopsis:    Short description of your package
description: Please see the README on Github at <https://github.com/DaisukeBekki/dynet-tools#readme>
author:      Daisuke Bekki
maintainer:  bekki@is.ocha.ac.jp
copyright:   Daisuke Bekki
license:     BSD3
github:      DaisukeBekki/dynet-tools
ghc-options: -Wall
extra-source-files:
  - README.md
  - ChangeLog.md
dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2
  - filepath >= 1.4
  - aeson >= 1.3
  - cereal >= 0.5
  - DyNet == 0.1.*
  - jsem >= 0.1.2
  - containers >=0.5
  - split >=0.2
  - shelly >=1.6
  - xml-conduit >=1.3
  - gnuplot >=0.5.5
  - hashable >=1.2
library:
  source-dirs: src
  exposed-modules:
  - DyNet.Tools.Utils
  - DyNet.Tools.Juman
  - DyNet.Tools.Chart
  - DyNet.Simple
  - DyNet.Simple.LSTMclassifier
  other-modules: []
executables:
  jsemClassify:
    main:         jsemClassify.hs
    source-dirs:  app/jsem
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: dynet-tools
  jsemTrain:
    main:         jsemTrain.hs
    source-dirs:  app/jsem
    ghc-options:  ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
    dependencies: dynet-tools
#  drel:
#    main: DRel.hs
#    source-dirs: app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - dynet-tools >=0.1.0.4
